### ISSUE TITLE
关于 batch size

### ISSUE THREAD

**Issue by liimy1** [jcchan23/GraphSol#10]
您好，非常感谢您的源代码提供，我已经复现了您的实验，我想请教一下我应该如何使用您的神经网络框架训练其他的数据集呢？
由于每一个蛋白质的序列长度不同，导致样本的尺寸不一样，所以batch size只能设置为1，但是当我训练自己的数据集时，loss一直不收敛，每个epoch的训练集loss一直为47左右，验证集为46，不发生变化，而输出每一步loss在几百-几千之间反复变化。我想请教一下，接下来我应该怎么做才可以解决这个问题呢？
期待您的回复，十分感谢！

**Comment by jcchan23** [comment]
非常感谢您关注到我们的文章，首先关于batch size为1的问题，我在readme中提到已经更新了一个新的基于dgl版本的graphsol，您可以去参考一下，dgl给蛋白质图做batch的基本原理是基于矩阵的对角线堆叠的方式，实现上直接是dgl.batch(graphs)，比较简单。关于第二个问题，我猜想是您使用的特征未进行标准化/归一化处理，不同维度的特征的量纲出现了较大差异，导致了loss出现了几百几千的情况，正常的训练下一般是不会出现这个量级的数字的(QM7例外)。

链接：(https://github.com/jcchan23/SAIL/tree/main/Repeat/GraphSol)
