### ISSUE TITLE
关于溶解度

### ISSUE THREAD

**Issue by kekehatui** [jcchan23/GraphSol#11]
请问你的溶解度数据是实际溶解度，还是可溶的概率。

**Comment by jcchan23** [comment]
它原文里面的定义是，蛋白质与水混合形成稳定体系后上清液占的比率，所以可能跟实际的溶解度（100g水能够溶解多少g蛋白质形成饱和溶液）这种有一点差异。但是基于这个定义可以将其转化为蛋白质与水混合形成稳定体系后发生溶解的概率。所以我在文章里以回归任务为主，但也可以有分类的指标。
