### ISSUE TITLE
请问您psi-blast用的nr90数据库是除冗余过的吗

### ISSUE THREAD

**Issue by kekehatui** [jcchan23/GraphSol#12]
是用什么方法除冗余的呢

**Comment by jcchan23** [comment]
具体是否除冗余过我也不是很清楚，是实验室前面的师兄师姐部署上去服务器的，感觉应该就是直接下载下来然后放上去的。

**Comment by kekehatui** [comment]
请问nr90数据库是多少个G，ncbi下载的nr数据库200来G

**Comment by jcchan23** [comment]
大概是这个数吧，具体多少我也不记得了，现在我也没有权限上去服务器查了，你按照psiblast的要求部署并且能够生成pssm文件就行，它是一个多序列比对算法，得到的特征不可能完全相同。
