### ISSUE TITLE
测试集问题

### ISSUE THREAD

**Issue by Zhen-Peng-Wu** [jcchan23/GraphSol#13]
同学你好，论文中提到的eSOL数据集，训练集和测试集个数分别为2052，685。但在GitHub中给出的训练集和测试集数目分别为2364，784。请问是我的理解有问题吗？
另外，酵母测试集原文件和特征文件能上传一下吗？

**Comment by jcchan23** [comment]
2364和784是所有对比方法都使用的数据集数量，它们都声称已经做了去同源，但是我自己使用25%去同源的时候发现还可以去掉一部分，而且最终结果也差异不大，所以就说了2052和685。数据集源文件和特征文件在毕业前已经提交给实验室了，我自己手里也没有备份了。
