### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by XUHANLIN** [jcchan23/GraphSol#2]
同学你好，我查阅文献的时候看到你的工作，目前也在做蛋白质相关的研究。想复线你这篇论文的实验，但是论文的用到的数据并没有给出，我看了文中数据集部分提到的参考文献也没有找到匹配的数据。不知道能否上传一下原始数据和几个特征数据文件呀

**Comment by jcchan23** [comment]
已经上传并且整理好了，感谢您的关注！
