### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by pengtb** [jcchan23/GraphSol#5]
Hi,
I want to repeat the results in the paper, but it seems that train/test datasets in /Data are only from eSOL dataset (S. cerevisiae dataset is not included) and are not clustered as mentioned in the paper.
So I wonder if train/test datasets in this respository could be directly used to repeat the results, or they need more preprocessing?

**Comment by jcchan23** [comment]
Thank you for following our work, you can cluster the train set by using CD-HIT or blastclust and the setting in the paper, and then run the code.  You can also run through the training process by using the datasets directly. Besides, the sequence of S.cerevisiae dataset could be found in the Solart paper, and the preprocess files will be uploaded after I come back to school.
