### ISSUE TITLE
How long did it take you to get a PSSM file and a HMM file, respectively?

### ISSUE THREAD

**Issue by Wenjian-Ma** [jcchan23/GraphSol#6]
Hi! May I know the running time to get a PSSM file and a HMM file by PSI-BLAST and HH-Suite3, respectively?

**Comment by jcchan23** [comment]
Thank you for your attention to our work. For a single protein sequence, it might cost 5~7 minutes for generating PSSM on average, and another 5 minutes for HMM on average. Thus we suggest that you can integrate the total generation pipeline and then run it by 8 parallel processes.
