### ISSUE TITLE
关于结点特征归一化的问题

### ISSUE THREAD

**Issue by Wenjian-Ma** [jcchan23/GraphSol#7]
您好，我在查看您的源代码时，发现您对所有蛋白质的AAPHY7、PSSM、HMM、SPD33构成的特征矩阵统一求出了均值和标准差，从而进行特征归一化：
![image](https://user-images.githubusercontent.com/35370756/145589397-9a07d23d-89c9-4d11-873e-a07d2139b5e7.png)
但Blosum62的均值和标准差是直接加载的：
![image](https://user-images.githubusercontent.com/35370756/145589980-bfef9eed-9f6a-4abd-99d9-ff03e6db8180.png)
所以我想问一下，Blosum62的归一化是怎么进行的，是所有蛋白质的Blosum62特征下进行求Blosum62的均值和标准差，从而归一化吗？

**Comment by Wenjian-Ma** [comment]
期待您的回复，十分感谢！

**Comment by jcchan23** [comment]
Blosum62的归一化方式与另外几种节点特征相同，也是对所有蛋白质的Blosum62特征下求它的均值和标准差，函数修改一下就可以用了，当时写这里的时候特征不是同个时间做的所以实现时就分开了，你可以写在一起进行归一化，感谢！

**Comment by Wenjian-Ma** [comment]
十分感谢您的回复！还有一个小问题，您的论文中提到Blosum62的编码方式要好于one-hot编码，那如果使用one-hot编码作为特征，是否也需要用这种归一化方法进行处理呢

**Comment by jcchan23** [comment]
如果是one-hot编码的话，对列做归一化操作是没有意义的，没有必要做这种操作，你可以先读取其他节点特征，归一化之后再拼接one-hot特征。

**Comment by Wenjian-Ma** [comment]
那如果是0-1之间的概率分布，是否需要做这种归一化呢

**Comment by jcchan23** [comment]
0-1之间的概率分布的数是不是必须做我不太知道，但我一般都是做归一化的，做不做之间会差一点点性能。但是像PSSM和HMM这种原来的数值就有数量级的差距(PSSM一般值在-10到10之间，HMM一般值在0~9999之间)，这种是一定要做归一化的，不然会对训练有影响。
