### ISSUE TITLE
Feature generation parameters

### ISSUE THREAD

**Issue by LiorZ** [jcchan23/GraphSol#8]
Thanks for providing the implementation of GraphSol!

Could you please also provide the parameters for each of the feature generation steps?
i.e. what command line arguments did you use for psiblast and the other apps

**Comment by jcchan23** [comment]
Thanks for your attention to our work, the command line is shown below.

For PSSM, use blast-2.10.1+ software
`${psiblast} -db ${NR90} -num_iterations 3 -num_alignments 1 -num_threads ${ncpu} -query $2 -out ${basedir}/bla/$1/${fasta_name}.bla -out_ascii_pssm ${basedir}/pssm/$1/${fasta_name}.pssm`
where `${psiblast}` is the binary executable file compiled by software, `${NR90}` is the uniref90 database and `$1` is the folder name and `$2` is the fasta file.

For HMM, use hhusite-3.0-beta.3-Linux software
`${hhblits} -i $2 -ohhm ${basedir}/hhm/$1/${fasta_name}.hhm -oa3m $(dirname ${basedir})/A3M_DI_MAT/a3m/$1/${fasta_name}.a3m -d ${HHDB} -v 0 -maxres 40000 -cpu ${ncpu} -Z 0 -o ${basedir}/hhr/$1/${fasta_name}.hhr`
where `${hhblits}` is the binary executable file compile by software, `${HHDB}` is the uniclust30 database and `$1`,`$2` is the same meaning.

For SPIDER3/DCA/CCMPred/SPOT-Contact, we all use default parameters with the requirement input that has been shown in the README.md
